### PR TITLE
Feature #1466 - Add flags "approved" and "allow to record" in the user registration form

### PR DESCRIPTION
**Pull request by fbottin**
Added flags "approved" (just when "require registration approval" is required by the site) and "allow to record" in the user registration form used by admins.

refs #1466

### CODE REVIEW

**Comment by daronco** [comment]
I just realized that, if the user is automatically approved when created, we might not need the "approved" flag. We only need it if we want to create a user that's not approved yet, but that doesn't make much sense.

I will check and let you know later.

**Comment by daronco** [comment]
So, yeah, we won't need the "approved" flag in the form. Sorry for the extra work you had to do. We will leave the form with the "can record" flag only.

The problem reported is that the user is not being automatically approved when created, as he should be. So if you could take a look at why this is happening (even though there is a call to `@user.approve!` where I think should be the right place), the fix could also be included in this PR.

**Comment by fbottin** [comment]
So, I removed the flag "approved" from the form, restored the user controller as he was before and refactored the tests.

After take a look we proved that the user is being approved in the create action.

**Comment by daronco** [comment]
The confusion was that the admins receive an email saying that the user is waiting for approval, even though the user was already automatically approved. This should be fixed at http://dev.mconf.org/redmine/issues/1469.

**Pull request merged**
