### PR TITLE
Event corrections - cancel registration, login first when registering as annonymous and participant confirmation

### PR DESCRIPTION
**Pull request by lfzawacki**

### CODE REVIEW

**Comment by daronco** [comment]
Fixes:

* If a user cancels participation in an event, he should be redirected to the event's show, not to the list of participants in the event. Happened for a superuser.
* The participant confirmation email should be sent in background with resque.
* The message when a guest registers should be changed from "Successfully registered in the event" (something like this) to "Registration received. You will soon receive an email with instructions to complete your registration."
* The participant confirmation email is not using the default layout used for other emails. (See http://dev.mconf.org/redmine/issues/1297)

Improvements:

* In the list of participants in an event, it would be good to show all unconfirmed guests in a different area, or even in a different view. We need to somehow separate them from the participants that are really confirmed.
* Is there a way for us to show a guest that he is already registered? Maybe store something in the session, even if the user is not signed in, or a cookie. I'm not sure, but it's something we should think about.
* Instead of `ParticipantConfirmation`, wouldn't it be better to call it `EventConfirmation`?

**Comment by lfzawacki** [comment]
About the improvements:
* Good idea
* Maybe we could store a cookie and use it when the user is logged out, but then multiple users in the same device would get confusing.
* I like `ParticipantConfirmation` and `EventConfirmation` sounds like the event happening confirmation, I dunno.

**Comment by lfzawacki** [comment]
Pretty much done

**Comment by daronco** [comment]
Was anything done about the fixes?

* If a user cancels participation in an event, he should be redirected to the event's show, not to the list of participants in the event. Happened for a superuser.
* The participant confirmation email should be sent in background with resque.
* The message when a guest registers should be changed from "Successfully registered in the event" (something like this) to "Registration received. You will soon receive an email with instructions to complete your registration".
* The participant confirmation email is not using the default layout used for other emails. (See http://dev.mconf.org/redmine/issues/1297).
* When a guest registers, he should receive a link to cancel his participation. This link should be in the confirmation email.

**Pull request merged**
